# filterbank config
filterbank:
  fb_name: 'STFTFB'
  n_filters: 512
  kernel_size: 512
  stride: 256
metric_to_opt:
  metric: 'stoi'
training:
  half_lr: yes
optim:
  optimizer: adam
  lr: 0.0001
  betas:  [0.9, 0.999]
  weight_decay: 0.
data:
  rate: 16000